# Generated by Django 2.2.4 on 2019-08-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yana', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
